/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JRadioButton;

/**
 *
 * @author cetina
 */
public class MainForm extends javax.swing.JFrame {
    

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        comboBoxEstadoCivil.setSelectedIndex(-1);
        checkBach.setSelected(false);
        checkLic.setSelected(false);
        checkPos.setSelected(true);
        
    }
    int cuota;
    private void verificarNivelEscolar(JRadioButton boton){
        if (boton.isSelected() == true) {
            System.out.println("Nivel escolar : "
                    + ""+boton.getText());
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEscolar = new javax.swing.ButtonGroup();
        comboBoxEstadoCivil = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        checkBach = new javax.swing.JRadioButton();
        checkLic = new javax.swing.JRadioButton();
        checkPos = new javax.swing.JRadioButton();
        checkBoxBecado = new javax.swing.JCheckBox();
        checkBoxHomologado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Viudo", "Divorciado", " " }));
        comboBoxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEstadoCivilActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado Civil");

        grupoEscolar.add(checkBach);
        checkBach.setText("Bachillerato");
        checkBach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBachActionPerformed(evt);
            }
        });

        grupoEscolar.add(checkLic);
        checkLic.setText("Licenciatura");
        checkLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLicActionPerformed(evt);
            }
        });

        grupoEscolar.add(checkPos);
        checkPos.setText("Posgrado");
        checkPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPosActionPerformed(evt);
            }
        });

        checkBoxBecado.setText("Becado");
        checkBoxBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBecadoActionPerformed(evt);
            }
        });

        checkBoxHomologado.setText("Homologado");
        checkBoxHomologado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxHomologadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkPos)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkLic)
                                    .addComponent(checkBach))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxBecado)
                                    .addComponent(checkBoxHomologado))))
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBach)
                    .addComponent(checkBoxBecado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkLic)
                    .addComponent(checkBoxHomologado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPos)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEstadoCivilActionPerformed
        String estadoCivil = (String) comboBoxEstadoCivil.getSelectedItem();
        System.out.println(estadoCivil);
    }//GEN-LAST:event_comboBoxEstadoCivilActionPerformed

    private void checkBachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBachActionPerformed
//        if (checkBach.isSelected() == true){
//            System.out.println("Nivel escolar: Bachillerato");
//        }
        this.verificarNivelEscolar(checkBach);
    }//GEN-LAST:event_checkBachActionPerformed

    private void checkLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLicActionPerformed
//        if (checkLic.isSelected() == true){
//            System.out.println("Nivel escolar: Licenciatura");
//        }
        
        this.verificarNivelEscolar(checkLic);
    }//GEN-LAST:event_checkLicActionPerformed

    private void checkPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPosActionPerformed
//        if (checkPos.isSelected() == true){
//            System.out.println("Nivel escolar: Posgrado");
//        }
        this.verificarNivelEscolar(checkPos);
    }//GEN-LAST:event_checkPosActionPerformed

    private void checkBoxBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBecadoActionPerformed
        if (checkBoxBecado.isSelected()){
            cuota = (int) 0.0;
            
        }else{
            cuota = (int) 100.0;
        }
        System.out.println("Cuota: "+ cuota);
    }//GEN-LAST:event_checkBoxBecadoActionPerformed

    private void checkBoxHomologadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxHomologadoActionPerformed
        if (checkBoxHomologado.isSelected()){
            cuota = (int) 80.0;
            
        }else{
            cuota = (int) 100.0;
        }
        System.out.println("Cuota: "+ cuota);
    }//GEN-LAST:event_checkBoxHomologadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton checkBach;
    private javax.swing.JCheckBox checkBoxBecado;
    private javax.swing.JCheckBox checkBoxHomologado;
    private javax.swing.JRadioButton checkLic;
    private javax.swing.JRadioButton checkPos;
    private javax.swing.JComboBox comboBoxEstadoCivil;
    private javax.swing.ButtonGroup grupoEscolar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
